[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
if = 0
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'mattn/ctrlp-launcher'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 't9md/vim-foldtext'

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'tpope/vim-fugitive'

